"""add published_at to announcements

Revision ID: 7a40266e503b
Revises: 006_notification
Create Date: 2026-02-25 02:26:22.404142
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a40266e503b'
down_revision = '006_notification'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'published_at')
    # ### end Alembic commands ###
