"""add actionkit_events

Revision ID: 018_add_actionkit_events
Revises: 017_drop_legacy_files
Create Date: 2026-03-10 10:21:05.368609
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '018_add_actionkit_events'
down_revision = '017_drop_legacy_files'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actionkit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('search_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['actionkit_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actionkit_events_created_at'), 'actionkit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_actionkit_events_event_type'), 'actionkit_events', ['event_type'], unique=False)
    op.create_index('ix_actionkit_events_item_created', 'actionkit_events', ['item_id', 'created_at'], unique=False)
    op.create_index('ix_actionkit_events_type_created', 'actionkit_events', ['event_type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_actionkit_events_type_created', table_name='actionkit_events')
    op.drop_index('ix_actionkit_events_item_created', table_name='actionkit_events')
    op.drop_index(op.f('ix_actionkit_events_event_type'), table_name='actionkit_events')
    op.drop_index(op.f('ix_actionkit_events_created_at'), table_name='actionkit_events')
    op.drop_table('actionkit_events')
    # ### end Alembic commands ###
