"""auto

Revision ID: 0cfaf7ebe7af
Revises: 20260220_06
Create Date: 2026-02-21 01:56:52.655884
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0cfaf7ebe7af'
down_revision = '20260220_06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_actionkit_categories_domain_slug'), 'actionkit_categories', type_='unique')
    op.drop_constraint(op.f('uq_actionkit_files_item_id_version'), 'actionkit_files', type_='unique')
    op.drop_index(op.f('ix_growthclubcomment_author_id'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubcomment_created_at'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubcomment_parent_id'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubcomment_post_id'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubpost_author_id'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpost_category'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpost_created_at'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpost_is_blinded'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpostlike_created_at'), table_name='growthclubpostlike')
    op.drop_index(op.f('ix_growthclubpostlike_user_id'), table_name='growthclubpostlike')
    op.create_index(op.f('ix_roadmap_created_at'), 'roadmap', ['created_at'], unique=False)
    op.create_foreign_key(None, 'roadmap', 'team', ['team_id'], ['id'])
    op.drop_constraint(op.f('roadmap_step_details_roadmap_step_id_key'), 'roadmap_step_details', type_='unique')
    op.alter_column('userprofile', 'experiences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('userprofile', 'awards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('userprofile', 'certificates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('userprofile_user_id_key'), 'userprofile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('userprofile_user_id_key'), 'userprofile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('userprofile', 'certificates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('userprofile', 'awards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('userprofile', 'experiences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.create_unique_constraint(op.f('roadmap_step_details_roadmap_step_id_key'), 'roadmap_step_details', ['roadmap_step_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'roadmap', type_='foreignkey')
    op.drop_index(op.f('ix_roadmap_created_at'), table_name='roadmap')
    op.create_index(op.f('ix_growthclubpostlike_user_id'), 'growthclubpostlike', ['user_id'], unique=False)
    op.create_index(op.f('ix_growthclubpostlike_created_at'), 'growthclubpostlike', ['created_at'], unique=False)
    op.create_index(op.f('ix_growthclubpost_is_blinded'), 'growthclubpost', ['is_blinded'], unique=False)
    op.create_index(op.f('ix_growthclubpost_created_at'), 'growthclubpost', ['created_at'], unique=False)
    op.create_index(op.f('ix_growthclubpost_category'), 'growthclubpost', ['category'], unique=False)
    op.create_index(op.f('ix_growthclubpost_author_id'), 'growthclubpost', ['author_id'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_post_id'), 'growthclubcomment', ['post_id'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_parent_id'), 'growthclubcomment', ['parent_id'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_created_at'), 'growthclubcomment', ['created_at'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_author_id'), 'growthclubcomment', ['author_id'], unique=False)
    op.create_unique_constraint(op.f('uq_actionkit_files_item_id_version'), 'actionkit_files', ['item_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_actionkit_categories_domain_slug'), 'actionkit_categories', ['domain', 'slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
