"""add tags tables

Revision ID: 20260221_07
Revises: 20260221_06
Create Date: 2026-02-21 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260221_07'
down_revision = '20260221_06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('growthclubtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growthclubtag_name'), 'growthclubtag', ['name'], unique=True)
    op.create_table('growthclubposttaglink',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['growthclubpost.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['growthclubtag.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('growthclubposttaglink')
    op.drop_index(op.f('ix_growthclubtag_name'), table_name='growthclubtag')
    op.drop_table('growthclubtag')
    # ### end Alembic commands ###
