"""add is_suspended to user

Revision ID: 22fe2ae2db5b
Revises: ce5972110b1d
Create Date: 2026-02-24 06:51:16.985714
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22fe2ae2db5b'
down_revision = 'ce5972110b1d'
branch_labels = None
depends_on = None


def upgrade() -> None:

    op.add_column('user', sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_user_is_suspended'), 'user', ['is_suspended'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_is_suspended'), table_name='user')
    op.drop_column('user', 'is_suspended')

    # ### end Alembic commands ###
