"""add_notification_deletion_and_resource

Revision ID: 55411e297395
Revises: 6c09298f1d2d
Create Date: 2026-02-26 01:18:17.908752
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55411e297395'
down_revision = '6c09298f1d2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('notification', sa.Column('resource_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notification_resource_id'), 'notification', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_resource_id'), table_name='notification')
    op.drop_column('notification', 'resource_id')
    op.drop_column('notification', 'is_deleted')
    # ### end Alembic commands ###
