"""add audit_log_reason to user

Revision ID: 5afb882f37a0
Revises: 7a40266e503b
Create Date: 2026-02-25 05:27:20.056002
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5afb882f37a0'
down_revision = '7a40266e503b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('audit_log_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'audit_log_reason')
    # ### end Alembic commands ###
