"""restore missing columns

Revision ID: 6c09298f1d2d
Revises: 006_notification
Create Date: 2026-02-25 07:47:17.663393
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '6c09298f1d2d'
down_revision = '006_notification'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('audit_log_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'audit_log_reason')
    op.drop_column('announcements', 'published_at')
    # ### end Alembic commands ###
