"""add user discipline history table

Revision ID: 6f84ea42b8f9
Revises: d1f4b5bc1755
Create Date: 2026-02-23 07:21:17.458317
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""add user discipline history table

Revision ID: 6f84ea42b8f9
Revises: d1f4b5bc1755
Create Date: 2026-02-23 07:21:17.458317
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f84ea42b8f9'
down_revision = 'd1f4b5bc1755'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_discipline_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('prev_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], name=op.f('fk_user_discipline_history_admin_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_discipline_history_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_discipline_history'))
    )
    op.create_index(op.f('ix_user_discipline_history_created_at'), 'user_discipline_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_discipline_history_user_id'), 'user_discipline_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_discipline_history_user_id'), table_name='user_discipline_history')
    op.drop_index(op.f('ix_user_discipline_history_created_at'), table_name='user_discipline_history')
    op.drop_table('user_discipline_history')
    # ### end Alembic commands ###
