"""Add target_author to AuditLog

Revision ID: ce5972110b1d
Revises: 39902e32c3a7
Create Date: 2026-02-24 03:11:30.853026
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'ce5972110b1d'
down_revision = '39902e32c3a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auditlog', sa.Column('target_author', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auditlog', 'target_author')
    # ### end Alembic commands ###
