"""add user status and report fields

Revision ID: d1f4b5bc1755
Revises: 20260223_01
Create Date: 2026-02-23 05:48:44.384177
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'd1f4b5bc1755'
down_revision = '20260223_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    # op.drop_table('langchain_pg_embedding')
    # op.drop_table('langchain_pg_collection')
    op.drop_constraint(op.f('uq_actionkit_categories_domain_slug'), 'actionkit_categories', type_='unique')
    op.drop_constraint(op.f('uq_actionkit_files_item_id_version'), 'actionkit_files', type_='unique')
    op.drop_index(op.f('ix_growthclubcomment_author_id'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubcomment_created_at'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubcomment_parent_id'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubcomment_post_id'), table_name='growthclubcomment')
    op.drop_index(op.f('ix_growthclubpost_author_id'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpost_category'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpost_created_at'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpost_is_blinded'), table_name='growthclubpost')
    op.drop_index(op.f('ix_growthclubpostlike_created_at'), table_name='growthclubpostlike')
    op.drop_index(op.f('ix_growthclubpostlike_user_id'), table_name='growthclubpostlike')
    op.create_index(op.f('ix_roadmap_created_at'), 'roadmap', ['created_at'], unique=False)
    op.create_foreign_key(None, 'roadmap', 'team', ['team_id'], ['id'])
    op.drop_constraint(op.f('roadmap_step_details_roadmap_step_id_key'), 'roadmap_step_details', type_='unique')
    op.add_column('user', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('user', sa.Column('report_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_report_count'), 'user', ['report_count'], unique=False)
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    op.alter_column('userprofile', 'experiences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('userprofile', 'awards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('userprofile', 'certificates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_constraint(op.f('userprofile_user_id_key'), 'userprofile', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('userprofile_user_id_key'), 'userprofile', ['user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('userprofile', 'certificates',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('userprofile', 'awards',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('userprofile', 'experiences',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_user_report_count'), table_name='user')
    op.drop_column('user', 'last_login_at')
    op.drop_column('user', 'report_count')
    op.drop_column('user', 'status')
    op.create_unique_constraint(op.f('roadmap_step_details_roadmap_step_id_key'), 'roadmap_step_details', ['roadmap_step_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'roadmap', type_='foreignkey')
    op.drop_index(op.f('ix_roadmap_created_at'), table_name='roadmap')
    op.create_index(op.f('ix_growthclubpostlike_user_id'), 'growthclubpostlike', ['user_id'], unique=False)
    op.create_index(op.f('ix_growthclubpostlike_created_at'), 'growthclubpostlike', ['created_at'], unique=False)
    op.create_index(op.f('ix_growthclubpost_is_blinded'), 'growthclubpost', ['is_blinded'], unique=False)
    op.create_index(op.f('ix_growthclubpost_created_at'), 'growthclubpost', ['created_at'], unique=False)
    op.create_index(op.f('ix_growthclubpost_category'), 'growthclubpost', ['category'], unique=False)
    op.create_index(op.f('ix_growthclubpost_author_id'), 'growthclubpost', ['author_id'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_post_id'), 'growthclubcomment', ['post_id'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_parent_id'), 'growthclubcomment', ['parent_id'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_created_at'), 'growthclubcomment', ['created_at'], unique=False)
    op.create_index(op.f('ix_growthclubcomment_author_id'), 'growthclubcomment', ['author_id'], unique=False)
    op.create_unique_constraint(op.f('uq_actionkit_files_item_id_version'), 'actionkit_files', ['item_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_actionkit_categories_domain_slug'), 'actionkit_categories', ['domain', 'slug'], postgresql_nulls_not_distinct=False)
    op.create_table('langchain_pg_collection',
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey')),
    sa.UniqueConstraint('name', name=op.f('langchain_pg_collection_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('langchain_pg_embedding',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.create_index(op.f('ix_cmetadata_gin'), 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
