"""add cascade delete to foreign keys

Revision ID: f5b7b12c3036
Revises: 14f4520463f5
Create Date: 2026-02-23 07:53:24.769520
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5b7b12c3036'
down_revision = '14f4520463f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('growthclubcomment_post_id_fkey'), 'growthclubcomment', type_='foreignkey')
    op.drop_constraint(op.f('growthclubcomment_parent_id_fkey'), 'growthclubcomment', type_='foreignkey')
    op.create_foreign_key(None, 'growthclubcomment', 'growthclubcomment', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'growthclubcomment', 'growthclubpost', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('growthclubcommentreport_comment_id_fkey'), 'growthclubcommentreport', type_='foreignkey')
    op.drop_constraint(op.f('growthclubcommentreport_reporter_id_fkey'), 'growthclubcommentreport', type_='foreignkey')
    op.create_foreign_key(None, 'growthclubcommentreport', 'user', ['reporter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'growthclubcommentreport', 'growthclubcomment', ['comment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('growthclubpostreport_post_id_fkey'), 'growthclubpostreport', type_='foreignkey')
    op.drop_constraint(op.f('growthclubpostreport_reporter_id_fkey'), 'growthclubpostreport', type_='foreignkey')
    op.create_foreign_key(None, 'growthclubpostreport', 'growthclubpost', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'growthclubpostreport', 'user', ['reporter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'growthclubpostreport', type_='foreignkey')
    op.drop_constraint(None, 'growthclubpostreport', type_='foreignkey')
    op.create_foreign_key(op.f('growthclubpostreport_reporter_id_fkey'), 'growthclubpostreport', 'user', ['reporter_id'], ['id'])
    op.create_foreign_key(op.f('growthclubpostreport_post_id_fkey'), 'growthclubpostreport', 'growthclubpost', ['post_id'], ['id'])
    op.drop_constraint(None, 'growthclubcommentreport', type_='foreignkey')
    op.drop_constraint(None, 'growthclubcommentreport', type_='foreignkey')
    op.create_foreign_key(op.f('growthclubcommentreport_reporter_id_fkey'), 'growthclubcommentreport', 'user', ['reporter_id'], ['id'])
    op.create_foreign_key(op.f('growthclubcommentreport_comment_id_fkey'), 'growthclubcommentreport', 'growthclubcomment', ['comment_id'], ['id'])
    op.drop_constraint(None, 'growthclubcomment', type_='foreignkey')
    op.drop_constraint(None, 'growthclubcomment', type_='foreignkey')
    op.create_foreign_key(op.f('growthclubcomment_parent_id_fkey'), 'growthclubcomment', 'growthclubcomment', ['parent_id'], ['id'])
    op.create_foreign_key(op.f('growthclubcomment_post_id_fkey'), 'growthclubcomment', 'growthclubpost', ['post_id'], ['id'])
    # ### end Alembic commands ###
